input {
  kafka {
    bootstrap_servers => "kafka-0:9092,kafka-1:9092,kafka-2:9092"
    topics => ["earthquakes"]
    codec => json { charset => "UTF-8" }
    auto_offset_reset => "earliest"
  }
}

filter {
  mutate {
    remove_field => ["[event][original]", "@version", "event"]
    add_field => { "data_source" => "usgs" }
    rename => { "event_id" => "[@metadata][event_id]" }
  }

  # Construire geo_point "location" à partir de coordinates[lon, lat, depth]
  if [coordinates] and [coordinates][0] and [coordinates][1] {
    mutate {
      add_field => {
        "[location][lon]" => "%{[coordinates][0]}"
        "[location][lat]" => "%{[coordinates][1]}"
      }
    }
    mutate {
      convert => {
        "[location][lon]" => "float"
        "[location][lat]" => "float"
      }
    }
  }

  # Mettre la date de l'événement dans @timestamp
  if [time_iso] {
    date {
      match => ["time_iso", "ISO8601"]
      target => "@timestamp"
    }
  }

  # Optionnel: enlever le depth si tu ne l'utilises pas
  # mutate { remove_field => ["[coordinates][2]"] }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "earthquakes"
    document_id => "%{[@metadata][event_id]}"
    ssl_certificate_verification => false
  }
}